### ISSUE TITLE
Rocknoses and Brimstone

### ISSUE THREAD

**Issue by Judicioux** [Tirocupidus/TheExiledRPOverhaul#100]
Give rocknoses brimstone again. There's only a few actual nodes of the material on the entire map and they're returning a peculiarly small amount per hit. For example, using an iron pick, I was able to get 187 brimstone from 15-20 nodes. Considering that 1 brimstone = 1 steel, and these nodes take a bit to respawn, this could effectively render steel an unreasonable material.

**Comment by CupcakeValkyrie** [comment]
How about we just fix brimstone nodes so that they provide a reasonable amount of brimstone? Or is that beyond the scope of the mod?

**Comment by Judicioux** [comment]
Brimstone is an extremely limited resource without rocknoses having it. I searched every area of the salt flats for it. I know of only two caves that have a solid amount of it across the entire map. If it were a resource that created something very particularly powerful (like the mats needed for explosive jars), I, personally, would support it being available in such a limited capacity. But steel is, frankly, the baseline endgame material. On top of that, it isn't even the best anymore, other materials are more valuable. So my opinion is that it should be available via other means than the very limited appearances of brimstone nodes. I am mostly thinking in terms of when the server becomes even more populous than it already is. It will make steel such a limited commodity that it won't be worth having. What's the point of having a steel pick if, every time you go to get brimstone, all of the nodes have already been mined and you have no bars to repair it? Or make another one (depending on how the repair business plays out with the mod)? Eventually, it just may not be sensible to work with steel as there simply will not be enough to go around even for a single clan.

Also, I believe the mod can alter resource nodes.

**Comment by gjpeebles** [comment]
Vanilla table has rocknoses with a 20% chance to give brimstone, and it seems to be working fine in the dev kit.

**Comment by Norseman055** [comment]
can confirm @Tirocupidus , i get brimstone from rocknoses just fine.
