### ISSUE TITLE
Northern Monsters have INSANE HP

### ISSUE THREAD

**Issue by Shadowcrafting** [Tirocupidus/TheExiledRPOverhaul#102]
all of the northern monsters, beasts ect, might need to have their hp tweeked alittle as they are seriouslly out of sync scaling wise.

**Comment by CraftsmasterKubilai** [comment]
I agree with this - northern monsters should be a bit more tough than their southern counterparts (standard wolves, for example, should be the same as hyenas - the fact that they spawn in packs make them tough enough - with worgs being, say, twice as tough). As it is, combat against northern monsters simply isn't FUN...

**Comment by gjpeebles** [comment]
Closing this, as it would be dealt with in a weapon/armor/NPC balance.
