### ISSUE TITLE
(Silly) Idea: Specialized Crossbow Bolt - Rejurvinating Delivery Bolt....

### ISSUE THREAD

**Issue by Shadowcrafting** [Tirocupidus/TheExiledRPOverhaul#103]
Effectively an Alloe potion delived via crossbow... and is injected into who it hits.... if it hits the backside, the dose grants 3 stacks of regeneration other wise 1 stack of regeneration? ;D

**Comment by gjpeebles** [comment]
If you get shot in the ass with a crossbow, you're going to take damage. For future suggestions like this, please discuss it on the Discord server first to see if people think it's a good idea.
