### ISSUE TITLE
Lock thrall slot in crafting stations

### ISSUE THREAD

**Issue by CraftsmasterKubilai** [Tirocupidus/TheExiledRPOverhaul#106]
Change the attributes of the thrall slot in crafting stations so that only the owner of the station can view, as well as add/remove the thrall. The "main" (item) slots should be accessible based on the container's current "locked/unlocked" attributes. This will allow players who want to leave their thralls "on display" for whatever reason (for example, to make their village seem more populated/animated) to do so without worrying that the thrall will be casually stolen by someone walking by. 

If the station is destroyed, the thrall should go into the loot bag (as currently happens).

**Comment by gjpeebles** [comment]
Disabling the thrall slot if the viewing character isn't the station owner. This allows anyone to view the thrall, but only owners can touch it while it's in the station. It will be in the next update.

**Comment by CraftsmasterKubilai** [comment]
Actually, Tiro, I'd recommend that a non-owner NOT be able to view the details of the thrall (if possible) when the crafting station 'container' is opened. The ideal implementation (IMHO) would be to simply **_suppress the visibility of the entire slot_** to non-owners, so they can't (as easily, anyway) ID 'high value' thralls for raiding, etc.  (they can still see the animated model of the thrall working away at the station and may be able to assume its level from that evidence, of course).

Naturally, the owner should be able to interact with the thrall slot in every way (view thrall name/level details, what the thrall can craft, etc.).  Thanks!

**Comment by gjpeebles** [comment]
It seems to me that being able to see the thrall IC, one would be able to judge their craftsmanship and have a decent idea of what they were capable of.

**Comment by CraftsmasterKubilai** [comment]
OK I see your point and I DO want to be able to have non-owners actually USE the thrall (to craft or to repair, if we end up going that route eventually), so I withdraw that comment. Thanks!
