### ISSUE TITLE
Southern replacements for certain black ice recipes.

### ISSUE THREAD

**Issue by mlloy** [Tirocupidus/TheExiledRPOverhaul#113]
Although i agree that star metal recipes should remain the same, requiring both a Northern and Southern resource to smelt into ingots, there is no reason hardened steel should remain a Northern resource.

I propose an alternative to black ice in the creation of hardened steel (essentially two ways of smelting) with demon blood (a resource about as rare as black ice, and generally harder to kill things that drop it than ice rocknoses), therefore providing access to competitive end-game arms and armor to southern tribes, while still requiring the best gear (star metal) to have both brimstone (south) and blackice (north) to smelt.

**Comment by Shadowcrafting** [comment]
Demon blood can be farmed from imps right now.

**Comment by mlloy** [comment]
Okay do you have a suggestion for southern replacement for black ice for hardened steel recipes?  Right now demon blood still seems the most appropriate.

**Comment by Shadowcrafting** [comment]
Mmm no idea

**Comment by CraftsmasterKubilai** [comment]
Isn't this currently implemented? I just made hardened steel last night using blood, not black ice...

**Comment by gjpeebles** [comment]
Yep, I'm just bad at maintaining Issue status. :P
