### ISSUE TITLE
Elephant head trophy is missing

### ISSUE THREAD

**Issue by Midnighit** [Tirocupidus/TheExiledRPOverhaul#116]
I can't craft the elephant trophy. Either it's somewhere in the wrong tree or you've forgotten to add it entirely.

**Comment by gjpeebles** [comment]
Neither the recipe nor the item exist in the game, as far as I can tell. Have you seen it somewhere?

**Comment by Midnighit** [comment]
Couldn't find it in vanilla either, false alarm, funcom will have to fix it first
