### ISSUE TITLE
Weapon Revamp and Building Damage

### ISSUE THREAD

**Issue by mlloy** [Tirocupidus/TheExiledRPOverhaul#118]
Not sure how I feel about knocking in a door with a spear.  Would request that the only wieldable weapons capable of damaging buildings be warhammers and perhaps maces.

**Comment by gjpeebles** [comment]
Aren't most non-door building pieces fairly resistant to all weapons now anyway?

**Comment by gjpeebles** [comment]
I think this would be difficult to implement, with little return. The one time I remember knocking in a door, I did it with a maul, hopefully people on an RP server will keep things like this in mind. ^^ Closing.
