### ISSUE TITLE
'Seductive Lay' Noises

### ISSUE THREAD

**Issue by Judicioux** [Tirocupidus/TheExiledRPOverhaul#119]
The animation is neat. But those noises become annoying after a minute or so. Is there any way to remove the audio portion of the emote?

**Comment by CupcakeValkyrie** [comment]
Yes, please.

**Comment by Shadowcrafting** [comment]
+100 yes please mute mute mute

**Comment by AlexandriaWolf** [comment]
Oh here it is! HURRAY!
