### ISSUE TITLE
Remove groaning/suffering noises from wheels of pain

### ISSUE THREAD

**Issue by CupcakeValkyrie** [Tirocupidus/TheExiledRPOverhaul#121]
The Wheel of Pain is an unfortunate necessity for anyone seeking to build and defend a holding due to the need for added defense and crafting bonuses. However, since some characters are not, canonically, slavers (Sanctuary specifically), we tend to RP that our thralls are defectors from other clans, random people we found and helped, mercenaries we've made deals with, or criminals working off their crimes.

Point being: Having a wheel with people constantly groaning, crying, and suffering nearby throws off the mood. Badly. If possible, please remove the sounds from the wheels. They're not really necessary, all things considered.

**Comment by mlloy** [comment]
Pls fix the heads too.

**Comment by CraftsmasterKubilai** [comment]
I second this - even slavers get tired of the weird-ass sex noises that come out of those ^%$#@! things...

**Comment by AlexandriaWolf** [comment]
While we're at it...can we please for the love of all the Hyborian gods GET RID of the stupid sounds characters now make when using the reclining "seduce" emote? It's the WORST!!!
