### ISSUE TITLE
Allow building mats to be 'refundable' like other placeables. 

### ISSUE THREAD

**Issue by CraftsmasterKubilai** [Tirocupidus/TheExiledRPOverhaul#124]
Given the wonkiness (still) of the building toolkit (crap like accidentally demolishing a foundation - and half the building it's resting on - when your cursor was firmly on top of a ^%$#@! wall torch or piece of furniture you're trying to pick up), it would be very nice if building components could be picked up and placed back in inventory just like other placeables like furniture, palisades, etc. 

I know this would make building things much "cheaper" than it is now, but guess it all comes down to what you'd like players to spend time on - I personally haven't RP'd that much because I've been spending a great deal of time building (and then RE-building) stuff for Sanctuary, getting frustrated when a carefully-planned wall won't work when a SINGLE ^%$#@! FOUNDATION is mysteriously un-placeable (then having to spend over an hour re-gathering resources to replace the stuff that needs to be moved a foot to the left). Yes you could say that it's more "realistic" that way, but I'd argue since we can't dig/alter the landscape in any way to get around these frustrating challenges that this would be a fair "quality of life" change.  

I've also encountered bugs (still) where making a repair to a structure is impossible because the engine won't let me replace the EXACT SAME BUILDING PIECE for whatever reason, forcing me to, at times, literally tear stuff down to the foundations and rebuild from the ground up, which isn't "realistic" either - this change won't fix that underlying engine wonkiness obviously, but it WILL make things a lot faster when a big tear/down/rebuild is required simply to make a fix to a balky roof tile or damaged foundation.

**Comment by gjpeebles** [comment]
I get where you're coming from, but I don't like the idea of being able to recover an entire building or base, and using it to build something else. Closing this for now unless this becomes a hot issue that people really want, or Arinoth wants it in.
