### ISSUE TITLE
Yellow lotus flower just looks pretty

### ISSUE THREAD

**Issue by gjpeebles** [Tirocupidus/TheExiledRPOverhaul#14]
Lotus needs something to do! Consider making it part of yellow dye or devising new potion(s) for it.

**Comment by TranslationErrors** [comment]
Maybe a poison of some sort? Something with a funky effect, or perhaps even randomised for fun ^^ Possible options:
- Corruption drain
- Very rarely: weird 'dreams' in the form of getting a random lore book (either ours or vanilla) text on your screen. Kinda like how medicine men drug themselves up to get 'visions' (Can that be nodded in?)

**Comment by gjpeebles** [comment]
For now, I'm just going to use it to replace ichor as the yellow dye ingredient. The stuff you mention is probably possible, but will take more work. If you'd like to see them, we can make a new issue to look at those possibilities. ^^
