### ISSUE TITLE
Torches are created with no HP. Cannot be recovered/repaired.

### ISSUE THREAD

**Issue by CupcakeValkyrie** [Tirocupidus/TheExiledRPOverhaul#141]
When built, torches spawn with zero HP. Since "Return to Inventory" requires the item to be fully repaired, they cannot be picked back up. However, the repair hammer shows them at 0/250 and lists no repair ingredients, thus they cannot be repaired. The only option is to Demolish, which gives no ingredients back.

Result: Torches can only be destroyed once placed, not recovered. This is confirmed to be an issue for both standing torches and wall-bracketed torches.

**Comment by gjpeebles** [comment]
Reporting it to Funcom, not going to fix in TERPO.
