### ISSUE TITLE
Can falling damage be adjusted via TERPO?

### ISSUE THREAD

**Issue by CraftsmasterKubilai** [Tirocupidus/TheExiledRPOverhaul#145]
It's kinda weak sauce when I fall like 6 feet off a gently sloping hill... into SAND... and lose 1/3 my health.  'Mighty barbarian' indeed (must be my weak knees from all that high school football?) 

Can it be turned down to, say, HALF of what is is now?

**Comment by gjpeebles** [comment]
No plans to nerf gravity.
