### ISSUE TITLE
Simple Shelter does not work

### ISSUE THREAD

**Issue by aapep** [Tirocupidus/TheExiledRPOverhaul#147]
After crafting a simple shelter, the actual game object is invisible, though you can hear the placement sound and warnings of overlapping.

**Comment by gjpeebles** [comment]
Wait, what? I swear it was working fine when I fixed it last night. Tested in SP even.

**Comment by CraftsmasterKubilai** [comment]
Confirmed that this is working fine as of Oct. 21 - I placed two of them at Sanctuary in prep for the Trade Faire with no issues. Suggest this ticket be closed.

**Comment by gjpeebles** [comment]
Worked fine for another as well, thanks for letting me know. Closing.
