### ISSUE TITLE
Custom Sharables

### ISSUE THREAD

**Issue by gjpeebles** [Tirocupidus/TheExiledRPOverhaul#18]
Cherry-pick some stuff from Sharables into TERPO since the amazing Death2Mongo made a tutorial video on how he did it.

**Comment by gjpeebles** [comment]
Keep everything lockable except wooden boxes, barrels, and crafting stations.

**Comment by gjpeebles** [comment]
Tie in a small alliance system. Characters should be able to hold 'E' on another character to add them or their clan to their clan's list of allies. Ability to add allies limited to clan officers.

**Comment by TranslationErrors** [comment]
The alliance system sounds amazing - would do a lot for RP, especially if it work on thralls too
