### ISSUE TITLE
Add more flavour items

### ISSUE THREAD

**Issue by TranslationErrors** [Tirocupidus/TheExiledRPOverhaul#26]
Add items that don't necessarily do anything but that might be cool for RP. Things like
- Gems
- Jewelry
- Charms/religious icons

Perhaps give some of them a buff effect (only hard to obtain ones gotten through events. Possible buff effects are health regen/anti Corruption)

**Comment by gjpeebles** [comment]
I'm going to leave this to specific DM requests for now, and close it. I'd love to see these kinds of items in the game, but I'd personally have to use existing art assets. That isn't necessarily a bad thing if they actually do something new though.
