### ISSUE TITLE
Make crafting flasks cheaper

### ISSUE THREAD

**Issue by Midnighit** [Tirocupidus/TheExiledRPOverhaul#36]
Suggestion: With how many things require flasks with TERPO compared to vanilla CE maybe it would make sense to make crafting them cheaper? Either making 1 instead of 2 crystals produce 1 glass or making 2 instead of 3 glass yield 1 flask would be viable options.

**Comment by gjpeebles** [comment]
I haven't been farming this wipe, so I don't have a good handle on it. I didn't even realize TERPO was vastly different in this. I'd thought before to add crystal back to rocknoses. Do you consider that to be viable as well?
