### ISSUE TITLE
Repairing items

### ISSUE THREAD

**Issue by gjpeebles** [Tirocupidus/TheExiledRPOverhaul#5]
Allow items to be repaired by the professions that can make them.

**Comment by gjpeebles** [comment]
FC has the repair code locked up. Jerks. From what I can tell, We'd either have to open repairing to everyone, or make a recipe for every broken item.

**Comment by gjpeebles** [comment]
I've found a way around this by removing the vanilla repair button, and adding my own to the armorer's bench and blacksmith's bench. I should have it working soon.

**Comment by dessemon** [comment]
It's seems possible to repair without the bench for armorer and blacksmith characters :)

**Comment by gjpeebles** [comment]
Closing this issue, and using #107 for comments.
