### ISSUE TITLE
Feat Point Overhaul

### ISSUE THREAD

**Issue by gjpeebles** [Tirocupidus/TheExiledRPOverhaul#50]
# Total Points
- 16 points total
- 2 every 5 levels

This allows you to get T3 at level 30, and all your points at level 40.

# Profession Costs
- T1: 1
- T2: 3
- T3: 8 (12 for Native/Priest)

This allows you to get one of the following combinations (not an exhaustive list):
- 1 T3 Native/Priest
- 1 T3 + 1 T2
- 4 T2

**Comment by TranslationErrors** [comment]
Looks good to me ^^
