### ISSUE TITLE
Cimmerian Battle-axe as a kind of Crom bonus

### ISSUE THREAD

**Issue by gjpeebles** [Tirocupidus/TheExiledRPOverhaul#52]
* Make the Cimmerian Battle-axe craftable only by T3 Cimmerian blacksmiths. (Not sure the best way to do this atm. It will likely be a separate, invisible feat that is added when a Cimmerian character takes T3 smithing.)
* Improve the damage, possibly other stats.
* Give Cimmerians a slight bonus when wielding it.
* Change T3 Cimmerian blacksmith thralls' special recipe to Exceptional Cimmerian Battle-axe.
* Change Maev the Magnificent's special recipe to a Flawless Cimmerian Battle-axe.

**Comment by TranslationErrors** [comment]
What about all the Stygian gear? Wouldn't it be odd to give one race a benefit that other's can't match? Other races have some weapons that fit them, or have their name, but not all of them.

**Comment by gjpeebles** [comment]
That's true. This started out because the Cimmerian Battle-axe is fairly useless compared to swords, except for RP. Then it occurred to me that followers of Crom receive no bonuses, and since those followers should primarily be Cimmerian... it sorta made sense as a potential religious bonus.

**Comment by TranslationErrors** [comment]
I like it better as a religion bonus vs a race bonus myself, though then again isn't that the point of Crom? He don't have no fucks to give and all that.

**Comment by gjpeebles** [comment]
Yeah. Maybe I should just alter the stats so it's a viable weapon, and leave the race/religion thing out of it. I do like Cimmerian thrall smiths being able to make exceptional/flawless versions though.

**Comment by gjpeebles** [comment]
Not going to do this, I think FunCom implemented their own exceptional/flawless versions and gave them to thralls.
