### ISSUE TITLE
Climbing stamina drain

### ISSUE THREAD

**Issue by gjpeebles** [Tirocupidus/TheExiledRPOverhaul#54]
Try to make a constant stamina drain while climbing, even while still.

**Comment by TranslationErrors** [comment]
Maybe survival can be renamed and can be used for the climbing skill instead? That way people who want to be good at climbing actually need to give up another important stat for it

**Comment by gjpeebles** [comment]
I think Survival is going to come into more play with the new biome and temperature system, so I'm avoiding making any changes to it until then. Also, I think it'd make more sense for strength to aid in climbing, but I don't think we need to help that stat any more. ;P
