### ISSUE TITLE
Possible TERPO-related bugs

### ISSUE THREAD

**Issue by ItsArinoth** [Tirocupidus/TheExiledRPOverhaul#61]
#1: Clothing sometimes does not render on character models.
#2: Opening inventory causes game to freeze for a moment.

**Comment by TranslationErrors** [comment]
2 - haven't noticed this myself. How many people are reporting this?

**Comment by ItsArinoth** [comment]
The clothing rendering started happening as I teleported to players. Had to restart my game to fix it.
The inventory opening issue is apparently a bug from the vanilla game.
