### ISSUE TITLE
Ymir Arrow Recipe Change

### ISSUE THREAD

**Issue by ItsArinoth** [Tirocupidus/TheExiledRPOverhaul#64]
Make the crafting recipe give ten arrows at the cost of 10 branches and 1 ice to bring it in line with our other arrow recipes.

**Comment by Morador** [comment]
I think this would be a nice start of balancing the Ymir religion out.
As it stands arrow deplete the shards way too quickly. I still think the making of Black Ice cost too much, when compared to farming nodes. But lowering the price of arrows, would at least mean there would be shards to spare for it.
