### ISSUE TITLE
Hardened Steel Greatsword

### ISSUE THREAD

**Issue by ScarletLoss** [Tirocupidus/TheExiledRPOverhaul#65]
Crafting this item does not consume materials or craft the item. Once the crafting finishes nothing happens.

**Comment by gjpeebles** [comment]
Worked okay in the devkit. I'm wondering if it happened due to server dropping.

**Comment by ScarletLoss** [comment]
I tried it multiple times and it never made a thing nor did it consume materials.

**Comment by gjpeebles** [comment]
Re-place your crafting station, i believe that will make it work.
