### ISSUE TITLE
Hoar-Frost Hatchet no longer provides ice crystal shards

### ISSUE THREAD

**Issue by Norseman055** [Tirocupidus/TheExiledRPOverhaul#66]
Confirmed harvesting 200+ lumber with 0 drops of crystal shards. Used to get about 3-5 per 100, but after clearing an entire portion of my valley of trees, I received 0 crystal shards.

**Comment by gjpeebles** [comment]
I suspect this has something to do with the change I'd made to harvesting hide with daggers only. I've reverted that temporarily, so I want to watch this to see if that fixes it.

**Comment by ScarletLoss** [comment]
Still not getting Ice Shards when harvesting lumber with a Hoar-Frost Hatchet
Just farmed about 400 wood without a single drop.

**Comment by gjpeebles** [comment]
I just chopped down one tree with a Hoar-Frost Hatchet and got an ice shard.

**Comment by gjpeebles** [comment]
5 trees now. I got ice shards on 4 of them. Where are the trees you were testing on?

**Comment by Norseman055** [comment]
Trees in the desert biome, by three forks (where the three rivers conjoin). I'll test again later today and see if you're reverted change fixed it.

**Comment by gjpeebles** [comment]
Looks like FunCom made it so you can only get shards from trees in the north.
