### ISSUE TITLE
Blank recipes

### ISSUE THREAD

**Issue by gjpeebles** [Tirocupidus/TheExiledRPOverhaul#67]
4 blank recipes before the black bear trophy in Woodsman T2

**Comment by mlloy** [comment]
So, about repairing items, it seems very strict that nothing is allowed to be repaired.  I think that repairing items should be allowed, but everytime it is repaired, the durability goes down.  So the weapon effectively becomes weaker and weaker and needs more and more repairs.  At some point it will just be worth it to go get another weapon and armor.
