### ISSUE TITLE
T4 thrall with flawless steel recipes (not hardened)

### ISSUE THREAD

**Issue by mlloy** [Tirocupidus/TheExiledRPOverhaul#70]
Found and tamed t4 thrall with flawless steel recipes (warhamemr + trident).

Despite having knowledge of the recipes as a t3 blacksmith I was not able to create the weapons.

**Comment by gjpeebles** [comment]
Thrall recipes are indeed broken atm. Trying to find a way to enable them without modding every item they can make.
