### ISSUE TITLE
Inverted Tiled Wedge Insulated Wooden Sloped Roof MIA

### ISSUE THREAD

**Issue by HonestAbe109** [Tirocupidus/TheExiledRPOverhaul#71]
I don't see it in my list of recipes. Should be with builder 2 feat?

**Comment by gjpeebles** [comment]
This and all the other new Pythagoras pieces. I'll ask for the new RecipesTable from the author.

**Comment by gjpeebles** [comment]
Uhhh whoops. This is a vanilla item. I see it now, it was swapped with the Black Ice piece. :P
