### ISSUE TITLE
Ice arrow recipe still 10 shards

### ISSUE THREAD

**Issue by mlloy** [Tirocupidus/TheExiledRPOverhaul#73]
This wasn't fixed at least in the tooltip, haven't tried to make.

**Comment by mlloy** [comment]
nvm I was looking at the bolts

**Comment by Midnighit** [comment]
Hardened steel and star metal arrows/bolts require 10 bars of their respective metal type to craft a single(!) arrow/bolt whereas it's just 1 bar per 10 arrows/bolts for steel and iron. Flinthead arrows/bolts require 10 stones per 10 arrows/bolts but I suppose that's working as intended with the higher availability of stones.

**Comment by Midnighit** [comment]
The hardened steel and star metal arrow/bolt recipes only require one bar to craft each but they still only produce a single arrow/bolt whereas all other arrow/bolt recipes produces 10 arrows/bolts

**Comment by gjpeebles** [comment]
Well that's stupid. I didn't bother checking the result quantity because it used 10 branches. Apparently vanilla wants 10 branches and 10 bars for 1 arrow.
