### ISSUE TITLE
Craftable iron/earthenware/wooden tableware consolidation

### ISSUE THREAD

**Issue by Midnighit** [Tirocupidus/TheExiledRPOverhaul#75]
There are several different models of Iron Bowls and Jugs spread over two blacksmithing tiers, partially handcrafted, partially crafted at the bench. I suggest consolidating them in tier and to either make them all handcrafted or all crafted at the bench.
If the recipes require different ingredients either pick one or give them slightly different names (e.g. T2 = Large Iron Pot, T1 = Small Iron Pot)
The Woodsman profession likely suffers from the same issue where it comes to tableware.

**Comment by gjpeebles** [comment]
The following items were added with the new biome, and seem to duplicate a chunk of what's in Tableware. I'll have a look at getting it all in order.
- Earthenware Jug
- Large Earthenware Jug
- Large Earthenware Jug
- Large Earthenware Jug
- Iron Bowl
- Iron Bowl
- Iron Bowl
- Iron Mug
- Iron Tankard
- Iron Pitcher
- Iron Decanter
- Iron Plate
- Iron Plate
- Wooden Bowl
- Wooden Bowl
- Wooden Bowl

**Comment by Midnighit** [comment]
Here's a list of all the affected items:
https://docs.google.com/spreadsheets/d/1YrzGfIzUtUx1brKn2uaSDWtWF9bzM-hahWwKeDibuTg/edit?usp=sharing (three sheets, one for blacksmith, builder and woodsman respectively)

I suggest to
1. have **all** of them either be hand crafted or crafted at a crafting station
1. either put them all to T1 or have different names for the T1 and T2 items
1. make items with the same name require the same materials

**Comment by Midnighit** [comment]
The Iron Bowl (80649) is now T1 but still requires 20x iron bar + 1x ichor as opposed to the 5x iron bar of all other iron bowls. You might either want to rename it to Large Iron Bowl or adjust the crafting cost.
