### ISSUE TITLE
Suggested update to brewing recipes

### ISSUE THREAD

**Issue by CupcakeValkyrie** [Tirocupidus/TheExiledRPOverhaul#78]
Brewing recipes currently have two issues:
1) They require too many resources, thus needing hours of farming to produce a halfway decent amount of alcohol. Alcohol has been fairly easy to obtain for over thousands of years...it shouldn't be rare.
2) Some make no sense, such as requiring ale to create mead.

## Ingredient recipes
**Desert Berry Pulp:** 10 desert berries.
**Highland Berry Pulp:** 10 highland berries.

### Purified water is omitted since it's needed for all drinks (1 each)
**Absinthe:** 10 Glowing Goop, 1 leavening agent.
**Ale:** 5 hops, 1 leavening agent.
**Cactus Wine:** 20 plant fiber, 1 leavening agent.
**Desert Wine:** 10 desert berry pulp, 1 leavening agent.
**Highland Wine:** 10 highland berry pulp, 1 leavening agent.
**Firewater:** 10 brimstone, 1 leavening agent.
**Wine:** 5 desert berry pulp, 5 highland berry pulp, 1 leavening agent.
**Honeyed Wine:** 1 wine, 5 honey, 1 leavening agent.
**Phykos Rum** 10 orange phykos, 1 leavening agent.
**Resin Wine:** 10 resin, 1 leavening agent.
**Shroom Beer:** 10 shroom amanita, 1 leavening agent.

**Comment by gjpeebles** [comment]
* Added mead as 10 honey, 1 leavening agent.
* Didn't mod the pulp recipes, but reduced the amount of pulp required in wine by 80%.
