### ISSUE TITLE
Crafting glass flasks

### ISSUE THREAD

**Issue by Midnighit** [Tirocupidus/TheExiledRPOverhaul#79]
Crafting glass flasks with a TERPO-enabled furnace isn't working very well.
In a vanilla furnace I put one glass flask mold and the desired amount of glass + fuel and turn it on. The furnace then keeps queuing up a single glass flask until it runs out of glass.
With a TERPO-enabled furnace and a single glass flask mold I can only queue up a single flask too but it won't auto-queue up more flasks. So if I want to craft 200 flasks (6 stacks of glass) I'd either need 200 glass flask molds or sit beside the furnace and keep queuing up single flasks.
Solution: If possible make the game consider a single mold as an infinite (or very large) number of flask molds for the purpose of crafting if that's possible. If that's not feasible, maybe remove the mold completely from the equation?

**Comment by gjpeebles** [comment]
Temporarily removing the mold from the recipe.

**Comment by Midnighit** [comment]
According to a report it now creates one mold for every flask you make.

**Comment by gjpeebles** [comment]
Oops. That makes sense since it always gave you your mold back.
