### ISSUE TITLE
The Native/Darfari tree

### ISSUE THREAD

**Issue by Midnighit** [Tirocupidus/TheExiledRPOverhaul#80]
The Darfari Sword (51853) requires a Blacksmith's Bench to craft, should be hand crafted like the rest. The Likewise Skeletal Decoration (80741) requires an Abyss of Yog to craft but I suppose that could be intentional since Darfari and Yog work fine together.
In general I believe the Native tree will need some love, not having access to any of the new FN items will make it even more difficult to compete with non-native characters. It stands to reason that the Darfari would be able to adjust to the cold of the north to some degree (they may be savage, but they're not stupid!).
edit: I also just realized that several armors in the native tree require (thick) leather to craft and there doesn't seem to be a way to craft a tannery or hand craft the required leather.

**Comment by gjpeebles** [comment]
Setting the sword and decoration to handcrafted, and changed the Abysmal dagger and sword to use leather instead of thick leather. Leaving the Native love for another issue.

**Comment by Midnighit** [comment]
Won't solve the issue of not being able to craft leather at all, will it?
