### ISSUE TITLE
Weaver tree suggestions/fixes

### ISSUE THREAD

**Issue by Midnighit** [Tirocupidus/TheExiledRPOverhaul#82]
- Stygian Vest, Shendyt and Sandals require light padding/lining whereas the other clothes don't require any padding/lining. It makes sense to me that clothes as opposed to real armor wouldn't require any padding. That'd be especially true to the light ones. If clothes armor and knockback defense get adjusted to real armor, this could be reevaluated for the better clothes.
- Assign similar heat insulation levels to the Relic Hunter set as is the case for the Shemite set.
- The crafted Relic Hunter set now has icons, it would be nice if those could be used for the crafting menu too.
- The two different color Tapestry versions (80551 and 80552), require different crafting mats: 25x leather + 10 twine for the original version and 30x silk for the new version.
- Yellow dye is back to requiring 5x brimstone, may or may not want to change that back to yellow lotus
- Maybe add exceptional/flawless versions of clothes, though I'm not sure through which means they'd be obtained (given that they're not crafted at an armorer's bench anymore)
- Add the "Fur Wrap" (or however it's actually called) and any other new northerner clothes to the weaver tree.

**Comment by gjpeebles** [comment]
Any in-game shots of this fur wrap thing might be needed. It's not just the fur armor?

**Comment by gjpeebles** [comment]
Holding on the insulation and exceptional/flawless stuff for now. Everything else should be in the next update.

**Comment by Midnighit** [comment]
I just don't like the idea that the most insulating (against heat) clothes in game is the light armor set when the shemite and relic hunter set look like they ought to be perfectly fine for the hot climate.

**Comment by CupcakeValkyrie** [comment]
Shemite and Relic Hunter look like desert clothes, which would be light and breathable, and pretty terrible for the cold.

**Comment by Midnighit** [comment]
That's what I meant to I say with **insulating against heat**. It might be a case of me miscommunicating, sorry. In any case the shemite set is worse against the desert heat than the (normal) light armor and the relic hunter set doesn't help at all. These are the stats of those sets respectively (keep in mind, more bars are better):
* Relic Hunter (0 bars spread over 5 items):
https://i.imgur.com/yPsIG6x.jpg
* Shemite (4 bars spread over 4 items):
https://i.imgur.com/94bBUYQ.jpg
* Light Armor (6 bars spread over 5 items):
http://i.imgur.com/Mcm5Iiq.jpg
* Flawless Light Armor (7 bars spread over 5 items):
http://i.imgur.com/c2dRvmQ.jpg

**Comment by gjpeebles** [comment]
Relic Hunter clothes should have (really) cooling properties in the next update.

Edit: no plans to add exceptional and flawless at this time.
