### ISSUE TITLE
Empty recipes in the crafting menu

### ISSUE THREAD

**Issue by Midnighit** [Tirocupidus/TheExiledRPOverhaul#85]
The first three recipes (Recipes 1938, 1931 and 1930) are empty.
[https://i.imgur.com/wNlYRVn.jpg](url)

**Comment by gjpeebles** [comment]
These were the poison meat recipes that I removed and completely forgot to mention in the notes or modify in the feat table.

**Comment by gjpeebles** [comment]
Apparently I did remember to remove them from the Survivor feat, but it seems they get tied to the character, so even a lotus potion keeps them there. I'll need to make my own potion again (and test it thoroughly) or remove the recipes in the database.
