### ISSUE TITLE
Provisioner suggestions/fixes

### ISSUE THREAD

**Issue by Midnighit** [Tirocupidus/TheExiledRPOverhaul#87]
* Recipes that could go to the native tree: Bug Kabob (18254), Darfari Bug Soup (18234)
* Recipes 18221 and 18262 both result in the creation of the same item (18221). Either adjust the ingredients for both or remove one.
* The recipe for Cimmerian Meal (T1/18242) requires Mead (T2/18076) to cook. I suggest either moving the meal one tier up or the mead one down.
* Ingredients made at the Fluid Press don't actually require the user to be provisioner even when the feat suggests they should be. Ingredients affected by this are:
  * Desert Berry Pulp (18033), Highland Berry Pulp (18032)
* Ingredients made at the Grinder or Dryer (currently bugged and working like a furnace) that are not assigned to a feat, can be made by everyone but look like they should belong to the provisioner are:
  * Salt (18263), Spice (18264), Dried Berries (18258)

**Comment by gjpeebles** [comment]
Leaving the press, grinder, and dryer to work like vanilla, but fixed the rest, and also fixed the dryer instruction image so it doesn't look like a furnace.

**Comment by gjpeebles** [comment]
I set campfires to require that crafting be queued in order to give Natives the bug recipes, but I failed to add all of the previously unknown recipes like gruel and cooked fish to Survivor. Need to do that.
