### ISSUE TITLE
Half of the Mitraen clothes from T1 craftable at T2 altar

### ISSUE THREAD

**Issue by Midnighit** [Tirocupidus/TheExiledRPOverhaul#89]
I'm not sure if itMitraen clothes available through T1: Mitraen Gloves (52523) and Mitraen Shoes (52525) are hand crafted, Mitraen Tunic (52522) and Mitraen Breeches (52524) require the T2 Altar of Mitra to craft.
Edit: Same applies to the Snake idol (TI 70001) and the Setite Shield (T2 51625) with Setites which both require a T3 Sanctum to craft.
The Statue of Ymir (T1 80757) is crafted at the T3 tempel.

**Comment by gjpeebles** [comment]
Setting the Mitraen Gloves and Shoes to be crafted at T2 altar, and moving recipes to appropriate feats so they match with that altars at which they're crafted.
