### ISSUE TITLE
Water-filled Flasks

### ISSUE THREAD

**Issue by gjpeebles** [Tirocupidus/TheExiledRPOverhaul#93]
Temporarily change flask recipe to reward water-filled flask until the water-filling bug is fixed. Also change back the few recipes I already set to require normal flasks to again require water-filled flasks.

**Comment by gjpeebles** [comment]
I forgot to set certain recipes (e.g. aloe extract) back to requiring water-filled flasks.

**Comment by Midnighit** [comment]
While you're at it - crafting light/dark dyes from a normal dye + dye colorant results in the light/dark dye + empty flask. Could this be changed to result in a full flask instead too?
