### ISSUE TITLE
Craftable shelters

### ISSUE THREAD

**Issue by gjpeebles** [Tirocupidus/TheExiledRPOverhaul#95]
Sayana - Today at 11:44 AM
These are the shelters I meant. Would be cool if we could craft them
[20170825171225_1.jpg](https://cdn.discordapp.com/attachments/299175586641870858/350681733412290560/20170825171225_1.jpg)

**Comment by Shadowcrafting** [comment]
Recommendation: T2 (woodworker, Builder, Savage)

Same HP an Hardness as a T2 foundation.

Mats needed
25 shaped wood
2 logs
18 rocks
1 barrel
